// Emoji categories with their display names
export interface EmojiItem {
  emoji: string;
  name: string;
}

export interface EmojiCategories {
  animals: EmojiItem[];
  food: EmojiItem[];
  transportation: EmojiItem[];
  sports: EmojiItem[];
  music: EmojiItem[];
  nature: EmojiItem[];
  hearts: EmojiItem[];
  faces: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategories = {
  animals: [
    { emoji: "🐶", name: "Dog Face" },
    { emoji: "🐱", name: "Cat Face" },
    { emoji: "🐭", name: "Mouse Face" },
    { emoji: "🐹", name: "Hamster" },
    { emoji: "🐰", name: "Rabbit Face" },
    { emoji: "🦊", name: "Fox" },
    { emoji: "🐻", name: "Bear" },
    { emoji: "🐼", name: "Panda" },
    { emoji: "🐨", name: "Koala" },
    { emoji: "🐯", name: "Tiger Face" },
    { emoji: "🦁", name: "Lion" },
    { emoji: "🐮", name: "Cow Face" },
    { emoji: "🐷", name: "Pig Face" },
    { emoji: "🐸", name: "Frog" },
    { emoji: "🐵", name: "Monkey Face" },
    { emoji: "🙈", name: "See-No-Evil Monkey" },
    { emoji: "🙉", name: "Hear-No-Evil Monkey" },
    { emoji: "🙊", name: "Speak-No-Evil Monkey" },
    { emoji: "🐔", name: "Chicken" },
    { emoji: "🐧", name: "Penguin" },
    { emoji: "🦄", name: "Unicorn" },
    { emoji: "🐝", name: "Honeybee" },
    { emoji: "🦋", name: "Butterfly" },
    { emoji: "🐌", name: "Snail" },
    { emoji: "🐙", name: "Octopus" },
    { emoji: "🦀", name: "Crab" },
    { emoji: "🐟", name: "Fish" },
    { emoji: "🐬", name: "Dolphin" },
    { emoji: "🦈", name: "Shark" },
    { emoji: "🐳", name: "Spouting Whale" },
    { emoji: "🦖", name: "T-Rex" },
    { emoji: "🦕", name: "Sauropod" },
  ],
  food: [
    { emoji: "🍎", name: "Red Apple" },
    { emoji: "🍌", name: "Banana" },
    { emoji: "🍇", name: "Grapes" },
    { emoji: "🍓", name: "Strawberry" },
    { emoji: "🍉", name: "Watermelon" },
    { emoji: "🍊", name: "Tangerine" },
    { emoji: "🍕", name: "Pizza" },
    { emoji: "🍔", name: "Hamburger" },
    { emoji: "🍟", name: "French Fries" },
    { emoji: "🌭", name: "Hot Dog" },
    { emoji: "🍿", name: "Popcorn" },
    { emoji: "🍩", name: "Doughnut" },
    { emoji: "🍪", name: "Cookie" },
    { emoji: "🎂", name: "Birthday Cake" },
    { emoji: "🍰", name: "Shortcake" },
    { emoji: "🧁", name: "Cupcake" },
    { emoji: "🍦", name: "Soft Ice Cream" },
    { emoji: "🍭", name: "Lollipop" },
    { emoji: "🍫", name: "Chocolate Bar" },
    { emoji: "🍬", name: "Candy" },
    { emoji: "\u2615\ufe0f", name: "Hot Beverage" },
    { emoji: "🥤", name: "Cup with Straw" },
  ],
  transportation: [
    { emoji: "🚗", name: "Automobile" },
    { emoji: "🚕", name: "Taxi" },
    { emoji: "🚙", name: "Sport Utility Vehicle" },
    { emoji: "🚌", name: "Bus" },
    { emoji: "🚎", name: "Trolleybus" },
    { emoji: "🏎️", name: "Racing Car" },
    { emoji: "🚓", name: "Police Car" },
    { emoji: "🚑", name: "Ambulance" },
    { emoji: "🚒", name: "Fire Engine" },
    { emoji: "🚐", name: "Minibus" },
    { emoji: "🚚", name: "Delivery Truck" },
    { emoji: "🚛", name: "Articulated Lorry" },
    { emoji: "🚜", name: "Tractor" },
    { emoji: "🛴", name: "Kick Scooter" },
    { emoji: "🚲", name: "Bicycle" },
    { emoji: "🛵", name: "Motor Scooter" },
    { emoji: "🏍️", name: "Motorcycle" },
    { emoji: "✈️", name: "Airplane" },
    { emoji: "🚁", name: "Helicopter" },
    { emoji: "🚀", name: "Rocket" },
    { emoji: "🛸", name: "Flying Saucer" },
    { emoji: "⛵", name: "Sailboat" },
    { emoji: "🚤", name: "Speedboat" },
    { emoji: "🛳️", name: "Passenger Ship" },
    { emoji: "⛴️", name: "Ferry" },
    { emoji: "🚢", name: "Ship" },
    { emoji: "⚓", name: "Anchor" },
  ],
  sports: [
    { emoji: "⚽", name: "Soccer Ball" },
    { emoji: "🏀", name: "Basketball" },
    { emoji: "🏈", name: "American Football" },
    { emoji: "⚾", name: "Baseball" },
    { emoji: "🎾", name: "Tennis" },
    { emoji: "🏐", name: "Volleyball" },
    { emoji: "🎱", name: "Pool 8 Ball" },
    { emoji: "🎯", name: "Bullseye" },
    { emoji: "🎲", name: "Game Die" },
  ],
  music: [
    { emoji: "🎸", name: "Guitar" },
    { emoji: "🎹", name: "Musical Keyboard" },
    { emoji: "🎺", name: "Trumpet" },
    { emoji: "🎻", name: "Violin" },
    { emoji: "🥁", name: "Drum" },
    { emoji: "🎤", name: "Microphone" },
    { emoji: "🎧", name: "Headphone" },
  ],
  nature: [
    { emoji: "⭐", name: "Star" },
    { emoji: "🌟", name: "Glowing Star" },
    { emoji: "💫", name: "Dizzy" },
    { emoji: "✨", name: "Sparkles" },
    { emoji: "🌈", name: "Rainbow" },
    { emoji: "☀️", name: "Sun" },
    { emoji: "🌙", name: "Crescent Moon" },
    { emoji: "⚡", name: "High Voltage" },
    { emoji: "🔥", name: "Fire" },
    { emoji: "💧", name: "Droplet" },
    { emoji: "🌊", name: "Water Wave" },
  ],
  hearts: [
    { emoji: "❤️", name: "Red Heart" },
    { emoji: "💛", name: "Yellow Heart" },
    { emoji: "💚", name: "Green Heart" },
    { emoji: "💙", name: "Blue Heart" },
    { emoji: "💜", name: "Purple Heart" },
    { emoji: "🖤", name: "Black Heart" },
    { emoji: "🤍", name: "White Heart" },
    { emoji: "💔", name: "Broken Heart" },
    { emoji: "💕", name: "Two Hearts" },
    { emoji: "💖", name: "Sparkling Heart" },
    { emoji: "💗", name: "Growing Heart" },
    { emoji: "💘", name: "Heart with Arrow" },
    { emoji: "💝", name: "Heart with Ribbon" },
  ],
  faces: [
    { emoji: "😀", name: "Grinning Face" },
    { emoji: "😂", name: "Face with Tears of Joy" },
    { emoji: "🥰", name: "Smiling Face with Hearts" },
    { emoji: "😎", name: "Smiling Face with Sunglasses" },
    { emoji: "🤔", name: "Thinking Face" },
    { emoji: "😴", name: "Sleeping Face" },
    { emoji: "🤯", name: "Exploding Head" },
    { emoji: "🥳", name: "Partying Face" },
    { emoji: "😭", name: "Loudly Crying Face" },
    { emoji: "😱", name: "Face Screaming in Fear" },
    { emoji: "🤗", name: "Hugging Face" },
    { emoji: "🤐", name: "Zipper-Mouth Face" },
    { emoji: "🥶", name: "Cold Face" },
    { emoji: "🥵", name: "Hot Face" },
    { emoji: "😇", name: "Smiling Face with Halo" },
    { emoji: "🤠", name: "Cowboy Hat Face" },
    { emoji: "🤡", name: "Clown Face" },
    { emoji: "👻", name: "Ghost" },
    { emoji: "👽", name: "Alien" },
    { emoji: "🤖", name: "Robot" },
    { emoji: "🎃", name: "Jack-O-Lantern" },
    { emoji: "💩", name: "Pile of Poo" },
    { emoji: "👾", name: "Alien Monster" },
  ],
};
